[package]
name = "litcat"
version = "0.1.0"
edition = "2024"
authors = ["Shan Shaji <shanshajiv@gmail.com>"]
description = "A CLI tool for viewing patches with colors"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
colored = "3.0"
